@extends('reports.common.template')

@section('title')
PO Report
@stop

@section('content')

<!--<div id="background">
  <p id="bg-text">NOT APPROVED</p>
	</div>-->

<div class="container" id="mainDiv">
  <div class="row" style="width:100%;">
    <div style="float:left; width:40%;">
      <h3 style="font-weight:bold; text-align:left;">Purchase Order</h3>
    </div>
    <div style="float:left;width:40%;">
      <div id="example2">
        <div style="font-weight:bold;font-size:16px;">Foundation Garments (Pvt) Ltd</div>
        <div>VAT NO: 114042005-7000 (Company Reg No:PV2646)</div>
        <div>No.35, Balapokuna Road, Colombo 05,SRI LANKA</div>
        <div>Tel:+94 11 4385400 Fax:+94 11 2769088</div>
        <div><b>E-Mail: b@helaclothing.com Web: www.fdnsl.com</b></div>
      </div>
    </div>
    <div style="float:left; width:20%;"><img src="{{ URL::asset('assets\images\logo.jpg') }}"/></div>
  </div>

  <div class="row style-details-1" style="width:100%;">
    <div style="float:left; width:40%;">
      <table class="table table-borderless">
        <tr>
          <th width="33%">PO Number</th>
          <th width="2%">:</th>
          <td width="65%">&nbsp;&nbsp;&nbsp;{{ $po }}</td>
        </tr>
        <tr>
          <th>PO Status</th>
          <th>:</th>
          <td>&nbsp;&nbsp;&nbsp;{{ $po_status }}</td>
        </tr>
      </table>
    </div>
    <div style="float:left;width:420;">
      <table class="right_tbl">
        <tr>
          <th class="tr" width="200">Deliver To</th>
          <td width="60%"><strong>{{ $loc_name }}</strong></td>
        </tr>
        <tr>
          <th class="tr" width="200"></th>
          <td width="60%">{{ $loc_address_1 }}</td>
        </tr>
        <tr>
          <th class="tr" width="200"></th>
          <td width="60%">{{ $loc_address_2 }}</td>
        </tr>
      </table>
    </div>

  </div>

  <div class="row style-details-1" style="width:100%;">
    <div style="float:left; width:40%;">
      <table class="table table-borderless">
        <tr>
          <th width="33%">PO Generated by</th>
          <th width="2%">:</th>
          <td width="65%">&nbsp;&nbsp;&nbsp;{{ $created_by }}</td>
        </tr>
        <tr>
          <th>Division of User</th>
          <th>:</th>
          <td>&nbsp;&nbsp;&nbsp;{{ $division }}</td>
        </tr>
      </table>
    </div>
    <div style="float:left;width:420;">
      <table class="right_tbl">
        <tr>
          <th class="tr" width="200">Invoice To</th>
          <td width="60%"><strong>{{ $company_name }}</strong></td>
        </tr>
        <tr>
          <th class="tr" width="200"></th>
          <td width="60%">{{ $company_address_1 }}</td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row style-details-1">
    <table class="table table-borderless">
      <tr>
        <th width="13%">Supplier Code</th>
        <th width="2%">:</th>
        <td width="25%">{{ $supplier_code }}</td>
        <th width="13%">Payment Method</th>
        <th width="2%">:</th>
        <td width="20%">{{ $payment_method_description }}</td>
        <!-- <th width="13%">Instruction</th> 
        <th width="2%">:</th>
        <td width="10%">{{ $instuction }}</td> -->
      </tr>

      <tr>
        <th>Supplier Name</th>
        <th>:</th>
        <td>{{ $supplier_name }}</td>
        <th>Payment Term</th>
        <th>:</th>
        <td>{{ $payment_description }}</td>
        <th>Deliver Date</th>
        <th>:</th>
        <td>{{$delivery_date}}</td>
      </tr>

      <tr>
        <th>Address</th>
        <th>:</th>
        <td>{{ $supplier_address1 }}</td>
        <th>Shipment Method</th>
        <th>:</th>
        <td>{{ $ship_mode }}</td>
        <th>VAT Reg No</th>
        <th>:</th>
        <td></td>
      </tr>

      <tr>
        <th></th>
        <th>:</th>
        <td>{{ $supplier_address2 }}</td>
        <th>Shipment Term</th>
        <th>:</th>
        <td>{{ $ship_term_description }}</td>
        <th></th>
        <th></th>
        <td></td>
      </tr>

      <tr>
        <th></th>
        <th>:</th>
        <td>{{ $supplier_city }}</td>
        <th></th>
        <th></th>
        <td></td>
        <th></th>
        <th></th>
        <td></td>
      </tr>

      <tr>
        <th></th>
        <th>:</th>
        <td>{{ $sup_country_name }}</td>
        <th></th>
        <th></th>
        <td></td>
        <th></th>
        <th></th>
        <td></td>
      </tr>
    </table>
  </div>

  <div class="row" style="margin-top:3px;">
    <table width="100%" align="center" border="1" id="listTbl">
      <tr>
        <td width="5%" align="center"><strong>Line No</strong></td>
        <td width="13%" align="center"><strong>Style</strong></td>
        <td width="5%" align="center"><strong>Item Code</strong></td>
        <td width="13%" align="center"><strong>Item Description</strong></td>
        <td width="13%" align="center"><strong>Comment</strong></td>
        <td width="7%" align="center"><strong>Delivery Date</strong></td>
        <td width="7%" align="center"><strong>Size</strong></td>
        <td width="7%" align="center"><strong>Item Color</strong></td>
        <td width="7%" align="center"><strong>Purchase UOM</strong></td>
        <td width="13%" align="center">
          <p><strong>Purchase Price ({{ $currency }}) </strong></p>
        </td>
        <td width="5%" align="center"><strong>Revise QTY</strong></td>
        <td width="5%" align="center"><strong>Value ({{ $currency }})</strong></td>
      </tr>
      {{ $tot = 0 }}
      {{ $req = 0 }}
      @foreach ($data as $d)
      {{ $split_tot = 0}}
      {{ $split_val = 0}}
      {{ $key = 0}}
      {{ $rowcount = 0}}
      @foreach ($count as $sp)
      @if($d->id == $sp->po_details_id)
      {{ $rowcount = count($split)+1}}
      {{ $split_tot = $sp->split }}
      {{ $split_val = $split_tot * $d->purchase_price }}
      @endif
      @endforeach

      <tr>
        <td align="center" rowspan="{{ $rowcount }}">{{ $d->line_no }}</td>
        <td align="center" rowspan="{{ $rowcount }}">{{ $d->style_no }}</td>
        <td align="left" rowspan="{{ $rowcount }}">{{ $d->master_code }}</td>
        <td align="left" rowspan="{{ $rowcount }}">{{ $d->master_description }}</td>
        <td  rowspan="{{ $rowcount }}"></td>
        <td align="center">{{ $d->del_date}}</td>
        <td align="center" rowspan="{{ $rowcount }}">{{ $d->size_name }}</td>
        <td align="center" rowspan="{{ $rowcount }}">{{ $d->color_name }}</td>
        @if($d->purchase_uom == null)
        <td align="center" rowspan="{{ $rowcount }}">{{ $d->uom_code }}</td>
        @else
        <td align="center" rowspan="{{ $rowcount }}">{{ $d->purchase_uom }}</td>
        @endif
        <td align="right"  rowspan="{{ $rowcount }}">{{ number_format($d->purchase_price,2) }}</td>
        <td align="right">{{ number_format(($d->req_qty - $split_tot),2) }}</td>
        @if(($d->tot_qty - $split_val) > 0)
        <td align="right">{{ number_format(($d->tot_qty - $split_val),2) }}</td>
        @else
        <td align="right">0.00</td>
        @endif
      </tr>
      @foreach ($split as $s)
      @if($d->id == $s->po_details_id)
      @foreach ($row_count as $row)
      @if($row->po_details_id == $s->po_details_id)
      @if($key == 0)
      <tr>
        <!-- <td rowspan="{{ $row->rowCount }}"></td> -->
        <td align="center">{{ $s->delivery_date }}</td>
        <!-- <td rowspan="{{ $row->rowCount }}"></td> -->
        <td align="right">{{ number_format($s->split_qty , 2) }}</td>
        <td align="right">{{ number_format(($d->purchase_price * $s->split_qty) , 2) }}</td>
      </tr>
      @else
      <tr>
        <td align="center">{{ $s->delivery_date}}</td>
        <td align="right">{{ number_format($s->split_qty , 2) }}</td>
        <td align="right">{{ number_format(($d->purchase_price * $s->split_qty) , 2) }}</td>
      </tr>
      @endif
      @endif
      @endforeach
      {{ $key = $key + 1 }}
      @endif
      @endforeach
      {{ $req += $d->req_qty }}
      {{ $tot += $d->tot_qty }}
      {{ $key = 0 }}
      @endforeach
      <tr>
        <td colspan="10" align="center"></td>
        <td align="right"><strong>{{ number_format($req,2) }}</strong></td>
        <td align="right"><strong>{{ number_format($tot,2) }}</strong></td>
      </tr>
    </table>
  </div>

  <div class="row" style="margin-top:2px;">
    <p>Value in Words: {{ $words }}</p>
    <h6 style="font-weight:bold; text-align:left;">Purchase Order Summary</h6>
  </div>

  <div class="row">
    <p>The table below is the summary of the materials to be purchased. Kindly note that the detailed items are illustrated above.</p>
    <table class="" width="100%" align="center" border="1" id="sumTbl">
      <tr>
        <td width="5%" align="center"><strong>Line No</strong></td>
        <td width="5%" align="center"><strong>Item Code</strong></td>
        <td width="13%" align="center"><strong>Item Description</strong></td>
        <td width="13%" align="center"><strong>Item Color</strong></td>
        <td width="7%" align="center"><strong>Delivery Date</strong></td>
        <td width="7%" align="center"><strong>Purchase UOM</strong></td>
        <td width="13%" align="center"><strong>Purchase Price ({{ $currency }})</strong></td>
        <td width="7%" align="center"><strong>Revise QTY</strong></td>
      </tr>
      @if(count($summary) != 0)
      @foreach($summary as $item)
      <tr>
        <td align="center">{{ $item->line_no }}</td>
        <td align="left">{{ $item->master_code }}</td>
        <td align="left">{{ $item->master_description }}</td>
        <td align="center">{{ $item->color_name }}</td>
        <td align="center">{{ $item->deli_date }}</td>
        @if($item->purchase_uom == null)
        <td align="center">{{ $item->uom_code }}</td>
        @else
        <td align="center">{{ $item->purchase_uom }}</td>
        @endif
        <td align="right">{{ number_format($item->purchase_price,2) }}</td>
        <td align="right">{{ number_format($item->req_qty,2) }}</td>
      </tr>
      @endforeach
      @elseif(count($sum_split) != 0)
      {{ $uniq_id = 0}}
      @foreach ($sum_split as $item)
      {{ $split_tot = 0}}
      {{ $bal_qty = 0}}
      @foreach ($count as $sp)
      @if($sp->po_details_id == $item->id)
      {{ $split_tot = $sp->split }}
      {{ $bal_qty = ($item->req_qty - $split_tot) }}
      @if($bal_qty > 0 && $item->id != $uniq_id)
      <tr>
        <td align="center">{{ $item->line_no }}</td>
        <td align="left">{{ $item->master_code }}</td>
        <td align="left">{{ $item->master_description }}</td>
        <td align="center">{{ $item->color_name }}</td>
        <td align="center">{{ $item->deli_date }}</td>
        @if($item->purchase_uom == null)
        <td align="center">{{ $item->uom_code }}</td>
        @else
        <td align="center">{{ $item->purchase_uom }}</td>
        @endif
        <td align="right">{{ number_format($item->purchase_price,2) }}</td>
        <td align="right">{{ number_format($bal_qty,2) }}</td>
      </tr>
      {{ $uniq_id = $item->id}}
      @endif
      @endif
      @endforeach
      <tr>
        <td align="center">{{ $item->line_no }}</td>
        <td align="left">{{ $item->master_code }}</td>
        <td align="left">{{ $item->master_description }}</td>
        <td align="center">{{ $item->color_name }}</td>
        @if($item->delivery_date == null)
        <td align="center">{{ $item->deli_date }}</td>
        @else
        <td align="center">{{ $item->delivery_date }}</td>
        @endif
        @if($item->purchase_uom == null)
        <td align="center">{{ $item->uom_code }}</td>
        @else
        <td align="center">{{ $item->purchase_uom }}</td>
        @endif
        <td align="right">{{ number_format($item->purchase_price,2) }}</td>
        @if($item->split_qty == null)
        <td align="right">{{ number_format($item->req_qty,2) }}</td>
        @else
        <td align="right">{{ number_format($item->split_qty,2) }}</td>
        @endif
      </tr>
      @endforeach
      @endif
      <tr>
        <td colspan="7" align="center"></td>
        <td align="right"><strong>{{ number_format($req,2) }}</strong></td>
      </tr>
    </table>
  </div>

  <p>&nbsp;</p>
  <div class="row">
    <table id="tbl4" width="100%">
      <tr>
        <td colspan="2">
          <ol>
            <li>This Agreement is the entire agreement between the Parties with respect to the supply of goods and supersedes all prior agreements and understanding with respect to this subject. This
              agreement may be amended only by written agreement executed by both Parties.
            </li>
            <li> Upon Delivery of the order, the Purchaser shall have the right to reject the Order in relation to the quantity delivered at any time. The Purchaser shall inform the Supplier at the time of the rejection
              only. The purchaser shall neither be liable to return any rejected quantities to the Supplier nor required to pay for same
            </li>
            <li>The Supplier hereby agrees to supply not in excess of + / - 3% per each line which shall not be greater than the total quantity shown in the purchase order. The Purchaser shall not be liable for
              any products shipped in excess of this limit. The Purchaser is not be liable to return to the Suppliers the excess products supplied by the Supplier over the agreed limit or will not be liable to pay for
              such quantities above the agreed excess limit .
            </li>
            <li> This purchase order is based on the technical specifications of the product as per the Supplier's Performa invoice, and shall not be deviated and/or amended in any manner what so ever, without
              the prior written approval of the Purchaser.
            </li>
            <li> The Supplier shall adhere strictly to the terms and conditions relating to price, delivery and packaging stipulated in the purchase order.
            </li>
            <li> Unless otherwise agreed in writing by the Purchaser and the Supplier, failure on the part of the Supplier to meet deadlines shall result in airing of the raw material entirely on the Supplier's
              account. The Supplier here by agrees to indemnify the Purchaser and hold the Purchaser saved and harmless against any delays and/or the Supplier's inability to meet deadlines.
            </li>
            <li>The Supplier shall submit originals of all mandatory laboratory test reports and shipping samples as required by the Purchaser, before any bulk shipment is affected.
            </li>
            <li> The Supplier shall not use any metal nails, pins, clips, staples or the likewise for the purpose of packing. The Supplier hereby ensures sand guarantees to the Purchaser that all cartons and
              packing materials shall be anti-metal. 9. Payment will be made on the agreed payment terms and in the currency stipulated in the purchase order.
            </li>
            <li> All suppliers from the SAARC region should send the GSP Certificate along with each shipment.
            </li>
            <li>All Suppliers from EU region should send the EUR1/ INF2 Certificates along with each shipment.
            </li>
            <li> Shipping Documents: Manually signed Commercial Invoice/Packing List & Original Bill of Lading should be couriered, If the BL is surrendered or if through Bank, Copy would be sufficient.Courier
              charges of the shipping documents should be on Supplier's account.
            </li>
            <li> Hard copies must reach us via courier (Preferred through DHL) within 7 days from the ETD. If the Sea transit is less than 7 days, please courier the Commercial Invoice/Packing List prior to the
              Sailing & surrender the Bill of Lading. Scanned copies of the same documents should reach us via e-mail within two days. If the above is not fulfilled there will be a charge back of US$50 per
              shipment & demurrages if any.
            </li>
            <li> Actual carton dimensions/Gross weight/ Net weight/ Volume weight should be clear marked on the Invoice & P/L. Shipping documents should be as per the correct INCO terms & Payment
              terms.
            </li>
            <li> Relevant HS Code per item should be marked in the Description column on the Commercial Invoice. Item Description should be clearly indicated (E.g. Knit Fabric , Elastics , Lace, etc ) on the
              Invoice. Ship Mode should be indicated on the Invoice.
            </li>
            <li> If the above (point 10 to 15) is not fulfilled there will be a charge back of US$ 50 per shipment & demurrages if any.
          </ol>
        </td>
      </tr>
      <tr>
        <td width="84%" scope="col">
          <p>&nbsp;</p><b>THIS IS A SYSTEM GENERATED DOCUMENT, SIGNATURES NOT REQUIRED<b>
        </td>
        <td width="16%" scope="col">
          <p>&nbsp;</p>Powered by&nbsp;<img width="10" height="10" src="{{ URL::asset('favicon1.jpg') }}" />&nbsp;Surface
        </td>
      </tr>
    </table>
  </div>
</div>

@stop
